### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by phosseini** [Xilorole/raptgen#12]
I could run `scripts/real.py` on my data and train a model successfully. Then I also could run `scripts/encode.py` to encode some sequences to their vector representations (exactly based on what is expected.) And I have a `embed_seq.csv` in the output with the right format. Now that I'm trying to **decode** a file using `scripts/decode.py` and the exact command in the readme, I get the following error:

```
saving to /content/drive/MyDrive/colab/RaptGen/out/decode
Traceback (most recent call last):
  File "scripts/decode.py", line 111, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "scripts/decode.py", line 53, in main
    arr = df.values[:,1:].astype(float)
ValueError: could not convert string to float: 'UGUAUAUGA'
```

Which I can see why this happens because `df.values[:,1:]` tries to also convert the actual sequence's _string_ to float. I changed the `df.values[:,1:]` to `df.values[:,2:]` so that we only convert the two-column vector representation of sequences, I don't get that error anymore, but this is the new error I get:

```
saving to /content/drive/MyDrive/colab/RaptGen/out/decode
loading model parameters
Traceback (most recent call last):
  File "scripts/decode.py", line 111, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "scripts/decode.py", line 58, in main
    model.load_state_dict(torch.load(model_path))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CNN_PHMM_VAE:
	size mismatch for decoder.tr_from_M.2.weight: copying a param with shape torch.Size([30, 32]) from checkpoint, the shape in current model is torch.Size([63, 32]).
	size mismatch for decoder.tr_from_M.2.bias: copying a param with shape torch.Size([30]) from checkpoint, the shape in current model is torch.Size([63]).
	size mismatch for decoder.tr_from_I.2.weight: copying a param with shape torch.Size([20, 32]) from checkpoint, the shape in current model is torch.Size([42, 32]).
	size mismatch for decoder.tr_from_I.2.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([42]).
	size mismatch for decoder.tr_from_D.2.weight: copying a param with shape torch.Size([20, 32]) from checkpoint, the shape in current model is torch.Size([42, 32]).
	size mismatch for decoder.tr_from_D.2.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([42]).
	size mismatch for decoder.emission.2.weight: copying a param with shape torch.Size([36, 32]) from checkpoint, the shape in current model is torch.Size([80, 32]).
	size mismatch for decoder.emission.2.bias: copying a param with shape torch.Size([36]) from checkpoint, the shape in current model is torch.Size([80]).
```

Looks like it can't load the trained model. Do you have any idea why this happens? (I'm running this on a Google Colab.) PS. I could run this code before on the very Google Colab, but now I can't reproduce it!

**Comment by lage2104** [comment]
Hi phosseini,
First a disclaimer, I am in no way associated with the project. But I work a lot with the code due to my master thesis (M. Sc. Computer Science). 
I had an similar issue. Which `target_len` are you providing for `scripts/decode.py`?
In my case I had to use the `target_len` which is calculated in 
`scripts/real.py` (https://github.com/Xilorole/raptgen/blob/c4986ca9fa439b9389916c05829da4ff9c30d6f3/scripts/real.py#L63)
and `scripts/encode.py` (https://github.com/Xilorole/raptgen/blob/c4986ca9fa439b9389916c05829da4ff9c30d6f3/scripts/encode.py#L37)
both.

Please let me know if that helped you :)!

**Comment by phosseini** [comment]
> Hi phosseini, First a disclaimer, I am in no way associated with the project. But I work a lot with the code due to my master thesis (M. Sc. Computer Science). I had an similar issue. Which `target_len` are you providing for `scripts/decode.py`? In my case I had to use the `target_len` which is calculated in `scripts/real.py` (
> 
> https://github.com/Xilorole/raptgen/blob/c4986ca9fa439b9389916c05829da4ff9c30d6f3/scripts/real.py#L63
> 
> )
> and `scripts/encode.py` (
> https://github.com/Xilorole/raptgen/blob/c4986ca9fa439b9389916c05829da4ff9c30d6f3/scripts/encode.py#L37
> 
> )
> both.
> Please let me know if that helped you :)!

Thanks for your response. For the decode, I'm using the default target length (20, in this case) with the very data they've provided. Model trains without any problem, and I can encode the sequences with no problem as well, but the decoding part throws the error. I printed the `target_len` computed during the encoding and it's `20` as well. So that doesn't seem to be the problem.

**Comment by lage2104** [comment]
I still have the feeling that this could cause the problem. Which dataset are you exactly using for `scripts/encode.py`? Is it `data/sample/sample.fasta` or another one? Same question for using `scripts/real.py`. Which dataset are you using?
And I am assuming the you are using a model which is stored somewhere in the `out/real` folder as a result of running `scripts/real.py`, right?

**Comment by phosseini** [comment]
> I still have the feeling that this could cause the problem. Which dataset are you exactly using for `scripts/encode.py`? Is it `data/sample/sample.fasta` or another one? Same question for using `scripts/real.py`. Which dataset are you using? And I am assuming the you are using a model which is stored somewhere in the `out/real` folder as a result of running `scripts/real.py`, right?

Thanks for the follow-up and the help. Finally made it work! Two things:

1. The path to the trained model I was using was wrong, so I fixed it (I was not initially reading the model from `out/real`). I also removed everything in the `out` folder and started fresh from scratch.
2. I still had to change the following line in the `decode.py`: `arr = df.values[:,1:].astype(float)` to `arr = df.values[:,2:].astype(float)`
